 //當滑鼠移到圖片時變亮度暗並顯示文字
 $(".bg_red").hover(function(){
    $(".bgm1").css("filter","brightness(40%)");
    $("#text1").css("display","block");
},function(){
    $(".bgm1").css("filter","brightness(100%)");
    $("#text1").css("display","none");
})
$(".bg_blue").hover(function(){
    $(".bgm2").css("filter","brightness(40%)");
    $("#text2").css("display","block");
},function(){
    $(".bgm2").css("filter","brightness(100%)");
    $("#text2").css("display","none");
})
$(".bg_gray").hover(function(){
    $(".bgm3").css("filter","brightness(40%)");
    $("#text3").css("display","block");
},function(){
    $(".bgm3").css("filter","brightness(100%)");
    $("#text3").css("display","none");
})